import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Shield, Activity, Layers, Radar, BookOpen, Bot, ArrowUpRight, ArrowRight, Upload, Download, Play, Search, Check, LockKeyhole, ChevronRight, CircleDot, FileJson, X, RefreshCw} from 'lucide-react';
import './style.css';
import Yunmai from './Yunmai';
import {parseIndicators} from './imports.mjs';

const nav = [{id:'overview',name:'事件研判',icon:Activity},{id:'assets',name:'资产发现',icon:Radar},{id:'knowledge',name:'研判知识库',icon:BookOpen},{id:'agent',name:'Pi 分析助手',icon:Bot},{id:'yunmai',name:'云脉 SASE',icon:Shield}];
const labels={critical:'严重',high:'高危',medium:'中危',low:'低危'};
function App(){
  const [token,setToken]=useState(''),[secret,setSecret]=useState(''),[page,setPage]=useState('overview');
  const [status,setStatus]=useState({}),[current,setCurrent]=useState(null),[history,setHistory]=useState([]),[selected,setSelected]=useState(null);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[importing,setImporting]=useState(false);
  const [format,setFormat]=useState('canonical'),[host,setHost]=useState(''),[logText,setLogText]=useState(''),[ti,setTi]=useState([]),[cfg,setCfg]=useState(null),[fileName,setFileName]=useState('');
  const [assetData,setAssetData]=useState({assets:[]}),[query,setQuery]=useState('service:http'),[limit,setLimit]=useState(50),[scope,setScope]=useState('{"networks":["192.0.2.1/24"],"domains":["example.test"]}');
  const [knowledgeQ,setKnowledgeQ]=useState('应急响应'),[refs,setRefs]=useState([]),[question,setQuestion]=useState('请依据事件证据解释攻击行为链、可能的误报，以及优先响应步骤。'),[consent,setConsent]=useState(false),[answer,setAnswer]=useState('');
  async function api(path,body,auth=token){const r=await fetch('/api'+path,{method:body===undefined?'GET':'POST',headers:{Authorization:'Bearer '+auth,...(body===undefined?{}:{'Content-Type':'application/json'})},...(body===undefined?{}:{body:JSON.stringify(body)})});if(!r.ok){let e;try{e=await r.json()}catch{e={detail:'服务暂时不可用'}}throw new Error(typeof e.detail==='string'?e.detail:JSON.stringify(e.detail))}return r.json()}
  async function task(fn){setBusy(true);setError('');setNotice('');try{await fn()}catch(e){setError(e.message)}finally{setBusy(false)}}
  function loadCase(c){setCurrent(c);setSelected(null);setAnswer('');setPage('overview')}
  async function connect(){await task(async()=>{const s=await api('/status',undefined,secret);setToken(secret);setStatus(s);const h=await api('/cases',undefined,secret);setHistory(h);if(h.length)loadCase(await api('/cases/'+h[0].id,undefined,secret));setAssetData(await api('/assets',undefined,secret))})}
  async function runDemo(){await task(async()=>{loadCase(await api('/demo',{}));setHistory(await api('/cases'));setNotice('合成演练数据已分析完成，未执行任何处置。')})}
  function saveJSON(name,obj){download(name,new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}))}
  function download(name,blob){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function readFile(file,fn){if(!file)return;if(file.size>4_000_000){setError('单个文件不能超过 4 MB');return}await task(async()=>fn(await file.text(),file.name))}
  const analysis=current?.analysis,plan=current?.plan,cases=analysis?.incidents||[],findings=analysis?.findings||[],actions=plan?.actions||[];
  const shown=selected?findings.filter(f=>f.host===selected):findings;
  const activeNav=nav.find(n=>n.id===page);
  if(!token)return <div className="login-screen"><div className="login-brand"><Shield size={30}/><span>Sentinel<span className="brand-zt">-ZT-CTTR</span></span></div><div className="login-card"><span className="eyebrow">EVIDENCE BEFORE ACTION</span><h1>让每次响应<br/>都有据可循。</h1><p>威胁情报 · 行为研判 · 零信任响应</p><label>工作台访问令牌<input autoComplete="off" type="password" placeholder="输入启动服务时配置的访问令牌" value={secret} onChange={e=>setSecret(e.target.value)} onKeyDown={e=>e.key==='Enter'&&connect()}/></label><button className="primary wide" disabled={busy||!secret} onClick={connect}>{busy?'正在连接…':'进入工作台'}<ArrowRight size={17}/></button>{error&&<div className="error">{error}</div>}<small><LockKeyhole size={13}/>令牌仅保存在当前页面内存中</small></div><div className="login-bottom">SENTINEL-ZT-CTTR / 0.2.1 <span>LOCAL-FIRST INCIDENT RESPONSE</span></div></div>;
  return <div className="shell"><aside className="sidebar"><div className="brand"><Shield size={27}/><span>Sentinel<span className="brand-zt">-ZT-CTTR</span></span></div><div className="workspace"><span className="workspace-icon">S</span><div>安全运营工作区<small>LOCAL WORKSPACE</small></div><LockKeyhole size={13}/></div><div className="nav-label">工作台</div><nav>{nav.map(({id,name,icon:Icon})=><button key={id} className={page===id?'nav-item active':'nav-item'} onClick={()=>{setPage(id);setError('');setNotice('')}}><Icon size={18}/>{name}{id==='overview'&&cases.length>0&&<span className="nav-count">{cases.length}</span>}</button>)}</nav><div className="sidebar-flow"><span className="nav-label">响应流程</span>{['汇集证据','关联行为','核验授权','执行与复核'].map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span>{s}</div>)}</div><div className="sidebar-footer"><span className="online-dot"/>本地策略引擎在线<small>v0.2.1 · 默认仅研判</small></div></aside>
  <div className="main-shell"><header className="topbar"><div className="breadcrumbs">安全运营 <ChevronRight size={13}/><strong>{activeNav.name}</strong></div><div className="topbar-right"><span className="local-pill"><LockKeyhole size={12}/>{status.deployment_mode==='yunmai'?'云脉后方工作台':'本地工作台'}</span><span className="avatar">IR</span></div></header><main>
  {error&&<div className="error banner">{error}<button onClick={()=>setError('')}><X size={15}/></button></div>}{notice&&<div className="notice"><Check size={16}/>{notice}</div>}
  <div className="page-heading"><div><div className="eyebrow">{page==='overview'?'INCIDENT INTELLIGENCE':page==='assets'?'EXTERNAL ATTACK SURFACE':page==='knowledge'?'INVESTIGATION REFERENCES':page==='yunmai'?'YUNMAI / CONTROLLED ACCESS':'PI AGENT / ASSISTED TRIAGE'}</div><h1>{activeNav.name}</h1><p>{page==='overview'?'把分散的安全线索，连接成可解释的响应依据。':page==='assets'?'发现暴露服务，确认资产归属，补全事件上下文。':page==='knowledge'?'从技术文章中找到研判线索，保留每一条来源。':page==='yunmai'?'通过云脉保护工作台入口，将行为证据交给授权人员复核处置。':'围绕当前事件，解释证据、澄清不确定性、制定响应步骤。'}</p></div><div className="heading-actions">{page==='overview'&&<><button className="secondary" disabled={busy} onClick={runDemo}><Play size={15}/>演练示例</button><button className="primary" disabled={busy} onClick={()=>setImporting(true)}><Upload size={16}/>导入日志</button></>}</div></div>
  {busy&&<div className="working"><RefreshCw size={14} className="spin"/>正在处理，请稍候…</div>}
  {page==='overview'&&<>
    <div className="stats-grid">{[{name:'分析事件',value:analysis?.statistics?.analyzed_events||0,icon:Layers,foot:'有效窗口内的唯一事件'},{name:'检测线索',value:findings.length,icon:Activity,foot:'行为规则与情报命中'},{name:'高风险资产',value:cases.filter(c=>c.risk>=70).length,icon:Shield,foot:'需要优先核验与响应'},{name:'待授权动作',value:actions.filter(a=>a.executable).length,icon:LockKeyhole,foot:'已通过策略前置校验'}].map((s,i)=><div className="stat" key={s.name}><div className="stat-top"><span>{s.name}</span><s.icon size={17}/></div><strong className={i===2&&s.value?'warm':''}>{s.value}<small>{i===2?'台':'项'}</small></strong><div className="stat-foot"><span className={'tiny-dot tone-'+i}/>{s.foot}</div></div>)}</div>
    <div className="content-grid"><div><section className="panel"><div className="panel-head"><h2>优先研判 <span>{cases.length}</span></h2>{selected&&<button className="text-button" onClick={()=>setSelected(null)}>显示全部</button>}</div>{!current?<div className="empty"><Radar size={38}/><h3>开始一次有依据的研判</h3><p>导入日志和威胁情报，或加载内置演练示例。</p><button className="secondary" onClick={runDemo}>加载合成演练数据<ArrowRight size={14}/></button></div>:cases.length===0?<div className="empty"><Check size={32}/><h3>当前规则未发现异常</h3><p>请同时检查日志覆盖率与有效时间窗口。</p></div>:<div className="case-list">{cases.map(c=><button key={c.id} onClick={()=>setSelected(selected===c.host?null:c.host)} className={'case-row '+(selected===c.host?'selected':'')}><div className="case-symbol"><Shield size={21}/></div><div className="case-info"><div><strong>{c.host}</strong><span className={'severity '+c.severity}>{labels[c.severity]}</span></div><p>{c.rule_ids.join(' · ')}</p><small>{c.evidence_ids.length} 条证据 <span>·</span> 待核验</small></div><div className="case-score"><strong>{c.risk}</strong><small>风险分</small></div><ChevronRight size={15}/></button>)}</div>}</section>
    <section className="panel evidence-panel"><div className="panel-head"><h2>行为证据 <span>{shown.length}</span></h2><span className="subtle">{selected||'全部资产'}</span></div>{shown.length===0?<div className="quiet-empty">分析完成后，命中规则及证据将在这里呈现。</div>:shown.map(f=><details className="evidence" key={f.id}><summary><span className="rule-code">{f.rule_id}</span><span className="evidence-title">{f.title}<small>{f.host}</small></span><span className="signal-score">{f.score}</span><ChevronRight size={14}/></summary><div className="evidence-detail"><p>{f.rationale}</p><p className="subtle">误报场景：{f.false_positives}</p><div className="techniques">{f.attack.map(t=><span key={t}>{t}</span>)}</div><pre>{JSON.stringify(analysis.events.filter(e=>f.evidence_ids.includes(e.id)),null,2)}</pre>{f.intel.length>0&&<><h4>匹配情报</h4><pre>{JSON.stringify(f.intel,null,2)}</pre></>}</div></details>)}</section></div>
    <div><section className="panel response-panel"><div className="panel-head"><h2>响应计划</h2><LockKeyhole size={16}/></div><div className="response-note"><Shield size={17}/><div><strong>先核验，再处置</strong><p>计划生成不会改变目标系统。执行需独立授权，且受时效和资产范围约束。</p></div></div>{actions.filter(a=>!selected||a.host===selected).map(a=><div className="action-item" key={a.id}><div><span className={'action-dot '+(a.executable?'ready':'')}/><strong>{a.type==='block_peer'?'临时封禁对端':'人工调查与取证'}</strong></div><p>{a.host}{a.peer_ip&&<><ArrowRight size={12}/>{a.peer_ip}</>}</p>{a.ttl_seconds&&<small>有效 {a.ttl_seconds} 秒 · {a.executable?'需签名授权':a.gates.join(' / ')}</small>}{a.steps&&<ul>{a.steps.map(s=><li key={s}>{s}</li>)}</ul>}</div>)}{!actions.length&&<div className="quiet-empty">暂无响应计划</div>}{current&&<button className="secondary wide" onClick={()=>saveJSON('sentinel-zt-cttr-plan.json',plan)}><Download size={14}/>导出计划 JSON</button>}</section>
    <section className="intel-card"><div className="eyebrow">ZERO TRUST PRINCIPLES</div><h3>信任需要证据，<br/>权限需要边界。</h3><p>逐次验证身份、设备和资源授权。威胁情报提供上下文，行为证据支持判断。</p><button onClick={()=>setPage('agent')}>让 Pi 协助研判<ArrowUpRight size={16}/></button><div className="orbit"><Shield size={52}/></div></section>
    {current&&<section className="panel export-panel"><h3>事件材料</h3><p>离线报告包含证据、规则解释与响应计划。</p><button className="text-button" onClick={()=>task(async()=>{const r=await fetch('/api/cases/'+current.id+'/report',{headers:{Authorization:'Bearer '+token}});if(!r.ok)throw new Error('报告导出失败');download('sentinel-zt-cttr-report.html',await r.blob())})}>下载完整报告<ArrowUpRight size={14}/></button></section>}
    </div></div>{history.length>1&&<div className="history-select"><label>切换调查记录 <select onChange={e=>task(async()=>loadCase(await api('/cases/'+e.target.value)))} value={current?.id||''}>{history.map(h=><option key={h.id} value={h.id}>{new Date(h.created_at).toLocaleString()} · {h.incidents} 个事件</option>)}</select></label></div>}
  </>}
  {page==='assets'&&<><div className="integration-banner"><div className="integration-logo">Q</div><div><h3>360 Quake</h3><p>被动资产发现 · 服务指纹 · 暴露面上下文</p></div><span className={'connection '+(status.quake_configured&&status.scope_configured?'connected':'')}>{status.quake_configured&&status.scope_configured?'已配置':'等待配置'}</span></div><section className="panel form-panel"><h2>查询组织暴露面</h2><p className="subtle">检索范围由服务端 SENTINEL_SCOPE 限定。查询可能消耗你的 Quake 配额。</p><div className="search-row"><input aria-label="Quake 查询语法" value={query} onChange={e=>setQuery(e.target.value)}/><input aria-label="记录上限" type="number" className="limit" min="1" max="1000" value={limit} onChange={e=>setLimit(Number(e.target.value))}/><button className="primary" disabled={busy||!status.quake_configured||!status.scope_configured} onClick={()=>task(async()=>{setAssetData(await api('/assets/quake',{query,limit}));setNotice('资产查询完成，请核验归属和观测时间。')})}><Search size={15}/>查询资产</button></div><details className="offline"><summary>导入离线 Quake 服务数据</summary><label>资产范围 JSON<textarea value={scope} onChange={e=>setScope(e.target.value)} rows="3"/></label><label className="file-button"><Upload size={15}/>选择 Quake JSON<input type="file" accept=".json" onChange={e=>readFile(e.target.files[0],async text=>{const o=JSON.parse(text);setAssetData(await api('/assets/import',{records:Array.isArray(o)?o:o.data,scope:JSON.parse(scope)}));setNotice('离线资产已导入。')})}/></label></details></section><section className="panel"><div className="panel-head"><h2>发现的服务 <span>{assetData.assets.length}</span></h2><span className="subtle">资产发现不自动授予响应权限</span></div><div className="table-scroll"><table><thead><tr><th>IP / 端口</th><th>服务 / 域名</th><th>产品线索</th><th>观测时间</th><th>归属</th></tr></thead><tbody>{assetData.assets.map(a=><tr key={a.id}><td className="mono">{a.ip}:{a.port}</td><td>{a.service||'未知'}<small>{a.domains.join(', ')}</small></td><td>{a.products.join(', ')||'—'}</td><td>{a.observed_at?new Date(a.observed_at).toLocaleString():'未知'}</td><td><span className="status-tag">待核验</span></td></tr>)}</tbody></table>{!assetData.assets.length&&<div className="empty"><Radar size={32}/><p>查询或导入后查看组织的暴露服务。</p></div>}</div></section></>}
  {page==='knowledge'&&<><section className="panel form-panel"><div className="panel-head borderless"><div><h2>wechat 安全文章索引</h2><p className="subtle">来源：izj007/wechat · 索引标题与链接 · 文章内容需分析员核验</p></div><label className="file-button"><Upload size={15}/>导入 README<input type="file" accept=".md,.txt" onChange={e=>readFile(e.target.files[0],async text=>{const r=await api('/knowledge/index',{readme:text});setNotice('已索引 '+r.indexed+' 篇文章');setStatus({...status,knowledge_indexed:true})})}/></label></div><div className="search-row"><input aria-label="知识库关键词" value={knowledgeQ} onChange={e=>setKnowledgeQ(e.target.value)} placeholder="应急响应、Webshell、钓鱼、Jeecg…"/><button className="primary" disabled={busy} onClick={()=>task(async()=>{const r=await api('/knowledge/search?q='+encodeURIComponent(knowledgeQ));setRefs(r.results);if(!r.configured)setNotice('请先导入仓库 README，建立标题索引。')})}><Search size={15}/>检索资料</button></div></section><div className="reference-grid">{refs.map(r=><a className="reference" key={r.url} href={r.url.startsWith('https://github.com/izj007/wechat/')?r.url:'#'} target="_blank" rel="noreferrer"><BookOpen size={20}/><h3>{r.title}</h3><span>查看原文<ArrowUpRight size={14}/></span></a>)}</div>{!refs.length&&<div className="empty"><BookOpen size={32}/><p>按行为特征检索相关分析资料。</p></div>}</>}
  {page==='agent'&&<div className="agent-grid"><section className="panel form-panel"><div className="agent-title"><div className="agent-icon"><Bot size={26}/></div><div><h2>Pi 事件分析助手</h2><p className="subtle">受限工具 · 证据解释 · 人工决策</p></div><span className="status-tag">{status.agent_enabled?'已启用':'待配置模型'}</span></div><div className="context-strip"><CircleDot size={14}/>{current?`已关联当前调查 · ${cases.length} 个事件 · ${findings.length} 条线索`:'请先导入日志或加载演练示例'}</div><label>你想分析什么？<textarea rows="5" value={question} onChange={e=>setQuestion(e.target.value)}/></label><label className="consent"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/>将本次问题与脱敏摘要发送到已配置的模型服务</label><button className="primary" disabled={busy||!current||!consent||!status.agent_enabled} onClick={()=>task(async()=>{const r=await api('/agent',{case_id:current.id,question,consent_to_model:consent});setAnswer(r.text||'模型没有返回说明。')})}><Bot size={16}/>开始协助研判</button>{answer&&<div className="agent-answer"><span className="eyebrow">PI ANALYSIS / 建议需人工核验</span><div>{answer}</div></div>}</section><section className="panel form-panel agent-boundaries"><h3>可调用的能力</h3>{['读取脱敏事件摘要','解释已命中检测规则','查看当前响应计划'].map(x=><p key={x}><Check size={16}/>{x}</p>)}<hr/><p className="subtle">Agent 无权调用 Shell、读取任意文件、签署授权或执行封禁。</p><p className="subtle">原始日志、用户标识和 IP 不进入自动摘要。你在问题中主动输入的内容会发送给模型。</p></section></div>}
  {page==='yunmai'&&<Yunmai api={api} current={current} task={task} saveJSON={saveJSON}/>}
  <footer className="page-footer"><span><span className="online-dot"/>Sentinel-ZT-CTTR · 证据驱动的应急响应</span><span>React / FastAPI / Pi Agent</span></footer></main></div>
  {importing&&<div className="modal-backdrop"><section className="modal"><div className="panel-head"><h2>导入日志与情报</h2><button className="icon-button" onClick={()=>setImporting(false)}><X size={20}/></button></div><div className="form-panel"><div className="two-fields"><label>日志格式<select value={format} onChange={e=>setFormat(e.target.value)}><option value="canonical">标准 JSONL</option><option value="sysmon">Sysmon JSONL</option><option value="suricata">Suricata EVE</option><option value="nginx">nginx access log</option></select></label><label>被监测资产名<input value={host} onChange={e=>setHost(e.target.value)} placeholder="nginx / Suricata 必填"/></label></div><label className="dropzone"><Upload size={27}/><strong>{fileName||'选择日志文件'}</strong><span>JSONL / LOG · 最大 4 MB</span><input type="file" accept=".jsonl,.log,.txt,.json" onChange={e=>readFile(e.target.files[0],(t,n)=>{setLogText(t);setFileName(n)})}/></label><div className="two-fields"><label className="file-button"><FileJson size={15}/>{ti.length?`已载入 ${ti.length} 条情报`:'选择标准 IOC JSON'}<input type="file" accept=".json" onChange={e=>readFile(e.target.files[0],t=>{setTi(parseIndicators(t))})}/></label><label className="file-button"><Shield size={15}/>{cfg?'资产策略已载入':'选择资产策略 JSON'}<input type="file" accept=".json" onChange={e=>readFile(e.target.files[0],t=>setCfg(JSON.parse(t)))}/></label></div><p className="subtle">情报须包含来源、置信度和有效期。未注册资产可研判，但不产生可执行的响应计划。</p><button className="primary wide" disabled={busy||!logText} onClick={()=>task(async()=>{loadCase(await api('/analyze',{events_text:logText,indicators:ti,policy_config:cfg,format,host:host||null}));setHistory(await api('/cases'));setImporting(false);setNotice('分析已完成，未执行任何处置。')})}>开始分析<ArrowRight size={16}/></button></div></section></div>}
  </div>
}
createRoot(document.getElementById('root')).render(<App/>);
